name: Production Tag Deployment

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]'

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Vercel CLI
        run: npm install --global vercel@30.1.1

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production

      - name: Deploy To Production
        run: vercel deploy --prod
